# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: allergic-reaction # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs4.3
  profile: reactathon
  environment:
    OPEN_TABLE_ACCESS_TOKEN: 27037c67-f394-4cfd-ab51-069ac71132fb
    OPEN_TABLE_HOST: platform.otqa.com
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    GOOGLE_PLACE_API_KEY: AIzaSyDV9_lAg47ZYsABcpggl4NIIlRqLQYjS8M
    GOOGLE_PLACE_HOST: https://maps.googleapis.com/maps/api/place
    LONDON_LATITUDE: 51.5074
    LONDON_LONGITUDE: -0.1278
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/users"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/restaurants"

resources:
  Resources:
    UsersDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: users
    RestaurantsDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: restaurants

functions:
  promotionsForUser:
    handler: handler.testServerRender
    events:
      - http:
          path: promotionsForUser
          method: get

  placesearch:
    handler: googleplaceapis.autocompleteSearch
    events:
      - http:
          path: search
          method: get
          cors: true

  availability:
    handler: handler.availability
    events:
      - http:
          path: availability
          method: get
          cors: true

  listings:
      handler: handler.listings
      events:
        - http:
            path: listings
            method: get
            cors: true

  nameListings:
      handler: handler.listingsByName
      events:
        - http:
            path: listingsByName
            method: get
            cors: true

  getUsers:
      handler: handler.getUsers
      events:
        - http:
            path: getUsers
            method: get
            cors: true

  createUser:
      handler: handler.createUser
      events:
        - http:
            path: createUser
            method: post
            cors: true

  createRestaurant:
      handler: handler.createRestaurant
      events:
        - http:
            path: createRestaurant
            method: post
            cors: true

  getRestaurants:
      handler: handler.getRestaurants
      events:
        - http:
            path: getRestaurants
            method: get
            cors: true

  getUserPromotions:
      handler: handler.getUserPromotions
      events:
        - http:
            path: getUserPromotions/{user_id}
            method: get
            cors: true

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
  #  events:
  #    - http:
  #        path: foodie/hello
  #        method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
